name: Stress tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  TEMPORAL_TESTING_LOG_DIR: /tmp/worker-logs
  TEMPORAL_TESTING_MEM_LOG_DIR: /tmp/worker-mem-logs
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  stress-test:
    runs-on: [self-hosted]
    steps:
      - name: Print stuff
        run: 'echo hi'
      